### PR TITLE
Reduce gif size

### PR DESCRIPTION
**Pull request by alxwrd**
こんにちは :wave:!

This PR is an attempt to address #7 (The size of the captured gif animation is too large than expected).

The idea is to compare to frames, and only save the difference between them.

I've added a new constant: `GIF_TRANSPARENCY_COLOR` which is an extra color I've added to the palette to use as the color for transparency in the gif. I've set this to pure red for now, if you want it as something else, let me know.

Since working on this I noticed you created `utilities.py`. Would you prefer `_get_color_palette_index` and `_difference` to live there?

To get this to work, I have had to change the `optimize` kwarg when creating the gif to `False`. This is because with optimisation, any unused colors are removed from the palette. This was causing the `GIF_TRANSPARENCY_COLOR` to move to difference palette indexes for each frame, so it wasn't working correctly.

The exception here is simple gifs (hello pyxel example) have grown in size as they benefited from `optimize=True`.

|  master branch        |  reduced               |
|-----------------------|------------------------|
|  ![][master-jump]     |  ![][reduced-jump]     |
| 14.7 MB               | 11.0 MB                |
|  ![][master-hello]    |  ![][reduced-hello]    |
| 699 KB                | 1.35 MB                |
|  ![][master-bubbles]  |  ![][reduced-bubbles]  |
| 8.38 MB               | 6.19 MB                |

[master-jump]: https://i.imgur.com/hX9bg9t.gif
[master-hello]: https://i.imgur.com/CQFLcNj.gif
[master-bubbles]: https://i.imgur.com/jOxHA3m.gif

[reduced-jump]: https://i.imgur.com/BIWML2a.gif
[reduced-hello]: https://i.imgur.com/iC10rLn.gif
[reduced-bubbles]: https://i.imgur.com/9BRgGc8.gif

### CODE REVIEW

**Comment by kitao** [comment]
Thank you for the suggestion! I don't have an idea of this and it's very impressive. I'm really appreciate it.

However, please let me say selfish. Please check the size of each gif animation of the following link:
https://github.com/kitao/pyxel/tree/master/pyxel/examples/screenshots

These are the gif I re-compressed with the online gif animation tool and its sizes are less than 1MB.
Do you have any idea how to compress gifs to this level? I'm wondering I need to use other python module to make gif animation instead of PIL.

**Comment by alxwrd** [comment]
@kitao, that is better! Do you have a link to the website you used? I'd like to compare the inputs and outputs to see what it's doing.

**Comment by alxwrd** [comment]
@kitao So after looking into [iloveimg.com](www.iloveimg.com), I am certain it's using the same compression as [ezgif.com/optimize](ezgif.com/optimize).

```shell
$ ls -lh *.gif
-rw-r--r-- 1 alxwrd 1049089 2.3M Oct 16 14:14 ezgif.gif
-rw-r--r-- 1 alxwrd 1049089 2.3M Oct 16 14:14 iloveimg.gif
```

ezgif.com claims: "GIF compressor optimizes GIFs using gifsicle and [Lossy GIF](https://github.com/kornelski/giflossy) encoder, which implements lossy LZW compression."

gifsicle (and it's fork giflossy) is a C library and, as far as I can see, there isn't a Python module for it. (The ones I could find require gifsicle to be installed, they don't have Python bindings for the C library).

I am about to push some changes to slightly reduce the size of the files a bit more by cleaning up the palette.

|  previously        |  now                 |
|-----------------------|------------------------|
|  ![][master-jump]     |  ![][master-jump]     |
| 11.0 MB               | 10.5 MB                |
|  ![][master-hello]    |  ![][master-hello]    |
| 1.35 MB                |  802 KB               |
|  ![][master-bubbles]  |  ![][master-bubbles]  |
| 6.19 MB               |  5.6 MB               |


[master-jump]: https://i.imgur.com/hX9bg9tt.gif
[master-hello]: https://i.imgur.com/CQFLcNjt.gif
[master-bubbles]: https://i.imgur.com/jOxHA3mt.gif

**Comment by kitao** [comment]
Thank you! Let's talk about other ideas, especially how to use gifsicle in #80

**Pull request merged**
