### PR TITLE
Translate README.md into Korean

### PR DESCRIPTION
**Pull request by dora-0**
:D

### CODE REVIEW

**Comment by kitao** [comment]
Hi. Thank you for translation!

Let me confirm one thing.
Is it possible to catch up with the README changes of the future in a short time?

If possible, I'll merge your README in Korean and let you know when README changes from now on.
Otherwise I'll copy it to the Pyxel wiki for reference (means it can be outdated).

Anyway it is great help!

**Comment by dora-0** [comment]
Sure! I'd be glad to help out :D

**Comment by kitao** [comment]
OK. I merged it. Thank you!

**Comment by kitao** [comment]
I updated the README for the 1.3.0.
Could you update the README in Korean?

**Comment by dora-0** [comment]
I just created a pull request now. Please confirm :)

**Pull request merged**
