### PR TITLE
Translate README into spanish

### PR DESCRIPTION
**Pull request by ccmorataya**
Related issue #188

### CODE REVIEW

**Comment by kitao** [comment]
Hi @ccmorataya , Thank you for the translation!

Do you think it is possible to continue to translate the README in Spanish?
I'll update the README when I add the new future and my concern is all READMEs in each language can be catch up with it.
If it seems difficult, I'll upload the README in Spanish to the Pyxel wiki for reference instead of merging into the repository.

Please think about this.

**Comment by ccmorataya** [comment]
Hi @kitao sure, I can still update it in Spanish, just let me know when there's a change and I'll do my job 👍

**Comment by kitao** [comment]
Thank you!

**Comment by kitao** [comment]
Actually I updated the README for the 1.3.0.
Could you update the README in Spanish?
Thank you in advance!

**Pull request merged**
